app:
  settings: '{ "key11": "value11", "key22": "value22", "key33": "value33" }'
  settings1: '{ "key11": "value11", "key22": "value22", "key33": "value33" }'
ftp:
  base-url1: "ftp://user:password@ftp.example.com/"
  base-url2: "ftp://user:password@ftp.example.com/"
