version: 2.0

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers-legacy
    # where the command run
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    parallelism: 6
    steps:
      # git clone code from github excluded subModule
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Test and Assemble
          command: |
            gradle test
            gradle assemble

      - store_artifacts:
          path: build/libs

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
