/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whalefall_learncases_callc_HelloJNI */

#ifndef _Included_com_whalefall_learncases_callc_HelloJNI
#define _Included_com_whalefall_learncases_callc_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whalefall_learncases_callc_HelloJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_whalefall_learncases_callc_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
