:project-version: 0.0.1
:toc:
:toc-title:
:toc-placement!:
:toclevels: 4

====
[discrete]
== Table of Contents
---
toc::[]
====

== cases in mapstruct

=== Case 1 How to Write MapStruct Convert Name

If class fields begin like `xAxxx`, `xAbxxXxx` both in source class and target class, the first alphabet is lower one, and the second is upper one.
Although they represent the same field in the same class, you still need to map this field.

* `xAdress`
* `aAdress`
* `sMsgHello`
* `sMSG`

Here is a right converter to handle all the field mapping.

[source,java]
.MyConverter - it's a pitfall: target name must keep the original, and the source must keep the first alphabet as upper `@Mapping(target = "xAdress", source = "XAdress")`
----
@Mapper
public interface MyConverter {
    MyConverter INSTANCE = Mappers.getMapper(MyConverter.class);

    @Mapping(target = "xAdress", source = "XAdress")
    @Mapping(target = "aAdress", source = "AAdress")
    @Mapping(target = "sMsgHello", source = "SMsgHello")
    @Mapping(target = "sMSG", source = "SMSG")
    @Mapping(target = "ssr", source = "SSr")
    @Mapping(target = "smSgHello1", source = "smSgHello1")
    MapStructEntity2 entity2ToEntity1(MapStructEntity1 entity1);
}
----

=== Case 2 Wrong way to convert List

Wrong way to use the converter, most of the fields are missing from the converter.

[source,java]
.Copy the case1 converter just modified the type to List, instead of the original type.
----
@SuppressWarnings("unused")
@Mapper
public interface MyConverter1 {
    MyConverter1 INSTANCE = Mappers.getMapper(MyConverter1.class);

    @Mapping(target = "ssr", source = "SSr")
    @Mapping(target = "xAdress", source = "XAdress")
    @Mapping(target = "aAdress", source = "AAdress")
    @Mapping(target = "sMsgHello", source = "SMsgHello")
    @Mapping(target = "smSgHello1", source = "smSgHello1")
    @Mapping(target = "sMSG", source = "SMSG")
    List<MapStructEntity2> entity2ToEntity1(List<MapStructEntity1> entity1);
}
----

* Generate code below

[source,java]
.There are just two fields mapping, losing many fields
----
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-05-29T20:32:16+0800",
    comments = "version: 1.5.5.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-8.7.jar, environment: Java 17.0.7 (Oracle Corporation)"
)
public class MyConverter1Impl implements MyConverter1 {

    @Override
    public List<MapStructEntity2> entity2ToEntity1(List<MapStructEntity1> entity1) {
        if ( entity1 == null ) {
            return null;
        }

        List<MapStructEntity2> list = new ArrayList<MapStructEntity2>( entity1.size() );
        for ( MapStructEntity1 mapStructEntity1 : entity1 ) {
            list.add( mapStructEntity1ToMapStructEntity2( mapStructEntity1 ) );
        }

        return list;
    }

    protected MapStructEntity2 mapStructEntity1ToMapStructEntity2(MapStructEntity1 mapStructEntity1) {
        if ( mapStructEntity1 == null ) {
            return null;
        }

        MapStructEntity2.MapStructEntity2Builder mapStructEntity2 = MapStructEntity2.builder();

        mapStructEntity2.smSgHello1( mapStructEntity1.getSmSgHello1() );
        mapStructEntity2.name( mapStructEntity1.getName() );

        return mapStructEntity2.build();
    }
}
----

[source,java]
.You can write a single converter function first.
----
@SuppressWarnings("unused")
@Mapper
public interface MyConverter11 {
    MyConverter11 INSTANCE = Mappers.getMapper(MyConverter11.class);


    List<MapStructEntity2> listEntity2ToEntity1(List<MapStructEntity1> entity1);

    @Mapping(target = "ssr", source = "SSr")
    @Mapping(target = "xAdress", source = "XAdress")
    @Mapping(target = "aAdress", source = "AAdress")
    @Mapping(target = "sMsgHello", source = "SMsgHello")
    @Mapping(target = "smSgHello1", source = "smSgHello1")
    @Mapping(target = "sMSG", source = "SMSG")
    MapStructEntity2 entity2ToEntity1(MapStructEntity1 entity1);
}
----

=== Case 3 How to use qualifiedByName

`qualifiedByName` use in single bean conversion need the method annotation with `@Name("xxx")`.
When using in `List<Xxx>`, the method must not be marked with `@Named`.

[source,java]
.Use list, need not be marked with @Named
----
@SuppressWarnings("unused")
@Mapper
public interface MyConverter2 {
    MyConverter2 INSTANCE = Mappers.getMapper(MyConverter2.class);

    @Mapping(target = "ssr", source = "SSr", qualifiedByName = "ssr")
    List<MapStructEntity2> entity2ToEntity1(List<MapStructEntity1> entity1);

    default String ssr(String str) {
        return "hello srr";
    }
}
----

[source,java]
----
@SuppressWarnings("unused")
@Mapper
public interface MyConverter3 {
    MyConverter3 INSTANCE = Mappers.getMapper(MyConverter3.class);

    @Mapping(target = "ssr", source = "SSr", qualifiedByName = "ssr")
    MapStructEntity2 entity2ToEntity1(MapStructEntity1 entity1);

    @Named("ssr")
    default String ssr(String str) {
        return "hello srr";
    }
}
----

=== Case 4 where to put the static enum convert method

Declare function in enum class, call the method through the `@Named` method.

[source,java]
.Method in converter
----
@Named("getStatus")
static Status getStatus(String status) {
    return Status.getStatus(status);
}
----

[source,java]
.Method in Status enum
----
public static Status getStatus(String status) {
    return switch (status) {
        case "active" -> Status.A;
        case "closed" -> Status.C;
        default -> null;
    };
}
----

=== Case 5 @BeforeMapping and @AfterMapping usage

`@BeforeMapping` and `@AfterMapping`

Only can indicate one `@MappingTarget` Target, and the `@MappingTarget` parameter must be the converted target type.

Another warning is that the declaration of the target class must have all getters and setters.

Any point missed will generate the implementation not calling the `@BeforeMapping` and `@AfterMapping` annotation methods.

[source,java]
----
@SuppressWarnings("all")
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface MyConverter5 {
    MyConverter5 INSTANCE = org.mapstruct.factory.Mappers.getMapper(MyConverter5.class);

    @Named("getStatus")
    static Status getStatus(String status) {
        return Status.getStatus(status);
    }

    @SuppressWarnings("unused")
    @Mapping(target = "status", source = "entity3.status", qualifiedByName = "getStatus")
    MapStructEntity4 convert(MapStructEntity3 entity3, String haha);

    @BeforeMapping
    default void beforeMapping(@MappingTarget MapStructEntity4 entity4, MapStructEntity3 entity3) {
        if (entity3 == null) {
            return;
        }
        // if entity3 is null, then fill it with default value A
        if ( StringUtils.isEmpty(entity3.getStatus())) {
            entity3.setStatus("active");
        }
    }

    @AfterMapping
    default void afterMapping(@MappingTarget MapStructEntity4 entity4) {
        if (StringUtils.isEmpty(entity4.getName())) {
            entity4.setName("whalefall");
        }
        if (entity4.getStatus() == null) {
            entity4.setStatus(Status.A);
        }
    }
}
----
