== How to write mapstruct convert name

=== case1
If class field begin like `xAxxx`、`xAbxxXxx` both in source class and target class, the first alphabet is lower one, and the second is upper one, althought write the same field in same class, but also need map this field.

* `xAdress`
* `aAdress`
* `sMsgHello`
* `sMSG`

Here is a right converter to handle all the field mapping.

[source,java]
.MyConverter it's a pitfall target name must keep the original, and the source must be keep the first alphabet is upper `@Mapping(target = "xAdress", source = "XAdress")`
----
@Mapper
public interface MyConverter {
    MyConverter INSTANCE = Mappers.getMapper(MyConverter.class);

    @Mapping(target = "xAdress", source = "XAdress")
    @Mapping(target = "aAdress", source = "AAdress")
    @Mapping(target = "sMsgHello", source = "SMsgHello")
    @Mapping(target = "sMSG", source = "SMSG")
    @Mapping(target = "ssr", source = "SSr")
    @Mapping(target = "smSgHello1", source = "smSgHello1")
    MapStructEntity2 entity2ToEntity1(MapStructEntity1 entity1);
}
----

=== case2

wrong way to use the converter, most of the fields are missing from the converter.

[source,java]
.Copy the case1 converter just modified the type to List, instead of the original type.
----
@SuppressWarnings("unused")
@Mapper
public interface MyConverter1 {
    MyConverter1 INSTANCE = Mappers.getMapper(MyConverter1.class);

    @Mapping(target = "ssr", source = "SSr")
    @Mapping(target = "xAdress", source = "XAdress")
    @Mapping(target = "aAdress", source = "AAdress")
    @Mapping(target = "sMsgHello", source = "SMsgHello")
    @Mapping(target = "smSgHello1", source = "smSgHello1")
    @Mapping(target = "sMSG", source = "SMSG")
    List<MapStructEntity2> entity2ToEntity1(List<MapStructEntity1> entity1);
}
----

* generate code below

[source,java]
----
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2024-05-29T20:32:16+0800",
    comments = "version: 1.5.5.Final, compiler: IncrementalProcessingEnvironment from gradle-language-java-8.7.jar, environment: Java 17.0.7 (Oracle Corporation)"
)
public class MyConverter1Impl implements MyConverter1 {

    @Override
    public List<MapStructEntity2> entity2ToEntity1(List<MapStructEntity1> entity1) {
        if ( entity1 == null ) {
            return null;
        }

        List<MapStructEntity2> list = new ArrayList<MapStructEntity2>( entity1.size() );
        for ( MapStructEntity1 mapStructEntity1 : entity1 ) {
            list.add( mapStructEntity1ToMapStructEntity2( mapStructEntity1 ) );
        }

        return list;
    }

    protected MapStructEntity2 mapStructEntity1ToMapStructEntity2(MapStructEntity1 mapStructEntity1) {
        if ( mapStructEntity1 == null ) {
            return null;
        }

        MapStructEntity2.MapStructEntity2Builder mapStructEntity2 = MapStructEntity2.builder();

        mapStructEntity2.smSgHello1( mapStructEntity1.getSmSgHello1() );
        mapStructEntity2.name( mapStructEntity1.getName() );

        return mapStructEntity2.build();
    }
}
----

=== case3

qualifiedByName use in single bean conversion need the method annotation with @Name("xxx");When using in List<Xxx> the method must no marked with @Named.

[source,java]
.use list, need not marked with @Named
----
@SuppressWarnings("unused")
@Mapper
public interface MyConverter2 {
    MyConverter2 INSTANCE = Mappers.getMapper(MyConverter2.class);

    @Mapping(target = "ssr", source = "SSr", qualifiedByName = "ssr")
    List<MapStructEntity2> entity2ToEntity1(List<MapStructEntity1> entity1);

    default String ssr(String str) {
        return "hello srr";
    }
}
----

[source,java]
----
@SuppressWarnings("unused")
@Mapper
public interface MyConverter3 {
    MyConverter3 INSTANCE = Mappers.getMapper(MyConverter3.class);

    @Mapping(target = "ssr", source = "SSr", qualifiedByName = "ssr")
    MapStructEntity2 entity2ToEntity1(MapStructEntity1 entity1);

    @Named("ssr")
    default String ssr(String str) {
        return "hello srr";
    }
}
----

==== case4

declare function in enum class, call the method through the `@Named` method

[source,java]
.method in converter
----
    @Named("getStatus")
    static Status getStatus(String status) {
        return Status.getStatus(status);
    }
----

[source,java]
.method in Status enum
----
    public static Status getStatus(String status) {
        return switch (status) {
            case "active" -> Status.A;
            case "closed" -> Status.C;
            default -> null;
        };
    }
----

==== case5

`@BeforeMapping` `@AfterMapping`

[source,java]
.Only can indicate one @MappingTarget Target, and the @MappingTarget parameter must the converted target type. Another warning is that The declaration of the target class must have all getters and setters. Any point missed will generate the implementation not call the `@BeforeMapping` `@AfterMapping` annotation method.
----
@SuppressWarnings("all")
@Mapper(unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface MyConverter5 {
    MyConverter5 INSTANCE = org.mapstruct.factory.Mappers.getMapper(MyConverter5.class);

    @Named("getStatus")
    static Status getStatus(String status) {
        return Status.getStatus(status);
    }

    @SuppressWarnings("unused")
    @Mapping(target = "status", source = "entity3.status", qualifiedByName = "getStatus")
    MapStructEntity4 convert(MapStructEntity3 entity3, String haha);

    @BeforeMapping
    default void beforeMapping(@MappingTarget MapStructEntity4 entity4, MapStructEntity3 entity3) {
        if (entity3 == null) {
            return;
        }
        // if entity3 is null, then fill it with default value A
        if ( StringUtils.isEmpty(entity3.getStatus())) {
            entity3.setStatus("active");
        }
    }

    @AfterMapping
    default void afterMapping(@MappingTarget MapStructEntity4 entity4) {
        if (StringUtils.isEmpty(entity4.getName())) {
            entity4.setName("whalefall");
        }
        if (entity4.getStatus() == null) {
            entity4.setStatus(Status.A);
        }
    }
}
----
